# Generated by Django 5.0 on 2025-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_aboutus_feedback_date_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
