# Generated by Django 5.0 on 2025-09-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_carouselimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
